name: Publish to PyPI on release

on:
  release:
    types: [published]

jobs:
  build-and-publish:
    name: Publish package on PyPI
    runs-on: ubuntu-18.04
    steps:
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install twine
      run: python -m pip install twine --user
    - name: pwd
      run: pwd
    - name: ls
      run: ls
    - name: Build package
      run: python setup.py sdist
    - name: Upload to PyPI
      run: twine upload dist/* -u ${{ secrets.PYPI_USERNAME }} -p ${{ secrets.PYPI_PASSWORD }}
